server:
  port: 8008

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/TaskDB2
    username: postgres
    password: 123
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379